### PR TITLE
Break up 099_binary.t into 16 pieces that can be tested in parallel

### PR DESCRIPTION
**Pull request by demerphq**
This PR includes two fixes. The first reduces the time to test in parallel by about 45 seconds to a minute. It does this by breaking up the 099_binary tests into 16 chunks which can be tested in parallel. We would like this in the perl core codebase as we run very many tests and this one routinely is one of the longest running. By breaking it up we gain efficiencies, especially on CPU's with a lot of cores. 

The second fix silences experimental warnings in t/core_bools.t, the builtin:is_bool function is marked experimental.

### CODE REVIEW

**Comment by demerphq** [comment]
See https://github.com/Perl/perl5/pull/20643

**Comment by demerphq** [comment]
I fixed the failure on older perls and repushed just now.

**Comment by demerphq** [comment]
Not sure what is up with 5.8, will build one now to test

**Comment by demerphq** [comment]
Ah, 5.8 doesnt support defined-equals: `//=`, fixed.

**Comment by demerphq** [comment]
Woohoo. :-)

**Comment by charsbar** [comment]
Thank you very much!

**Comment by demerphq** [comment]
My pleasure. Appreciate the speedy response as well! Will you roll a release soon so I can update core?

**Comment by charsbar** [comment]
Shipped 4.13 now.

**Comment by demerphq** [comment]
Nice! I'll give it an hour or so and then do the comparable patch to core. Like I said, really appreciate the speedy response. Thanks for your help. FWIW, the way to access parallel test is: `prove -b -j16 t/*.t`, or in core `TEST_JOBS=16 make test_harness`

**Pull request merged**
