### PR TITLE
avoid indirect notation in test suite

### PR DESCRIPTION
**Pull request by atoomic**

### CODE REVIEW

**Comment by charsbar** [comment]
@atoomic  Is this for "Perl 7"?

**Comment by atoomic** [comment]
@charsbar indeed this will conform to standards we are going to introduce in p7.

**Comment by charsbar** [comment]
@atoomic Thanks for clarification.

**Comment by atoomic** [comment]
@charsbar would you mind releasing an updated version of JSON-PP on CPAN with the last changes so we could update blead with the last changes?
thanks

**Comment by charsbar** [comment]
@atoomic Shipped 4.05. Thanks for your nudge.

**Pull request merged**
